default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  username: <%= Rails.application.secrets[:database][:username] %>
  database: <%= Rails.application.secrets[:database][:name] %>
  password: <%= Rails.application.secrets[:database][:password] %>

stage:
  <<: *default
  host: <%= Rails.application.secrets[:database][:host] %>
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  database: <%= Rails.application.secrets[:database][:name] %>

test:
  <<: *default
  username: <%= Rails.application.secrets[:database][:username] %>
  database: <%= Rails.application.secrets[:database][:name] %>
  password: <%= Rails.application.secrets[:database][:password] %>

production:
  <<: *default
  host: <%= Rails.application.secrets[:database][:host] %>
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  database: <%= Rails.application.secrets[:database][:name] %>
