development:
  admin_name: First User
  admin_email: admin@sine
  admin_password: admin123
  domain_name: localhost:3000
  notify:
    cc: amolpujari@gmail.com, amolpujari@gmail.com 
  secret_key_base: 04a992c84652fcbee94c94f38f6f7fe50d437b53ddce2d7788d808b284790936841fad059865167c0a6e0e5d1f0baf07b3b1a4e90fe9b511285eb2fce16fb9cf
  smtp:
    :username: 'amolpujari@gmail.com'
    :password: '******'
    :domain: 'mail.google.com'
    :host: 'smtp.gmail.com'

